// The free-traffic playbook, ordered by impact-per-hour for a brand-new
// Malaysian insurance domain with no backlinks. Everything here costs RM0.
//
// This list exists because the audit engine cannot fix the site's real problem.
// The code is already clean; what's missing is that nothing on the internet
// points at annaprudential.com, so nothing has a reason to rank or cite it.

export const PLAYBOOK = [
  {
    id: 'gsc-submit-sitemap',
    phase: 'Get indexed',
    title: 'Submit the sitemap in Google Search Console',
    why: 'Your verification file is already live, so the property exists — but a verified property does nothing on its own. Submitting the sitemap is what actually queues your 40+ URLs for crawling.',
    how: 'search.google.com/search-console → pick annaprudential.com → Sitemaps → enter "sitemap.xml" → Submit. Then Indexing → Pages to watch coverage.',
    link: 'https://search.google.com/search-console',
    minutes: 5,
    impact: 'critical',
  },
  {
    id: 'gsc-inspect-request',
    phase: 'Get indexed',
    title: 'Request indexing for your 6 most important URLs',
    why: 'Manual URL inspection jumps the queue. For a new domain this is the difference between days and months.',
    how: 'In Search Console use URL Inspection on: /, /calculators/, /blog/, /products/, and your two strongest guides. Click "Request indexing" on each. Limit is ~10/day.',
    link: 'https://search.google.com/search-console',
    minutes: 10,
    impact: 'critical',
  },
  {
    id: 'bing-webmaster',
    phase: 'Get indexed',
    title: 'Add the site to Bing Webmaster Tools',
    why: 'Bing is small for humans but large for AI: it is the search index behind Microsoft Copilot and part of ChatGPT\'s search layer. Getting into Bing is the single fastest route to appearing in an AI answer.',
    how: 'bing.com/webmasters → Add site → import directly from Google Search Console (one click, no re-verification) → submit sitemap.',
    link: 'https://www.bing.com/webmasters',
    minutes: 5,
    impact: 'critical',
  },
  {
    id: 'indexnow',
    phase: 'Get indexed',
    title: 'Push all URLs via IndexNow',
    why: 'Instant, free notification to Bing, Yandex, Seznam and Naver. The dashboard does this for you on the Indexing tab.',
    how: 'Run it from the Live & Indexing tab. It generates a key file — commit and deploy that file first, then submit.',
    minutes: 3,
    impact: 'high',
  },
  {
    id: 'google-business',
    phase: 'Local authority',
    title: 'Create a Google Business Profile',
    why: 'Free, and the strongest local ranking asset that exists. "insurance agent near me" and Maps results come almost entirely from this. It also creates a verified entity that Google can link to your domain.',
    how: 'business.google.com → service-area business (you visit clients) → category "Insurance Agency" → add annaprudential.com as the website → verify by postcard/phone. Post weekly.',
    link: 'https://business.google.com',
    minutes: 30,
    impact: 'critical',
  },
  {
    id: 'social-profiles',
    phase: 'Entity building',
    title: 'Link the domain from every social profile',
    why: 'These are your first backlinks and, more importantly, they teach search engines and LLMs that "Annabel Ong" + "annaprudential.com" + "Prudential Malaysia" are one entity. Entity consistency is most of GEO.',
    how: 'Put the exact URL in the bio of TikTok (@annacakapinsurans), Instagram, Facebook page, LinkedIn, YouTube, Threads. Use identical name, phone and description everywhere.',
    minutes: 30,
    impact: 'critical',
  },
  {
    id: 'sameas-schema',
    phase: 'Entity building',
    title: 'Add every social URL to sameAs in your schema',
    why: 'sameAs is the explicit machine statement "these accounts are me". It is how knowledge graphs merge your profiles into one entity. Right now sameAs only lists prudential.com.my.',
    how: 'Ask Claude to add your TikTok, Instagram, Facebook, LinkedIn and YouTube URLs to the sameAs array in the InsuranceAgency and Person schema blocks.',
    minutes: 10,
    impact: 'high',
  },
  {
    id: 'directories',
    phase: 'Backlinks',
    title: 'List on free Malaysian business directories',
    why: 'Consistent name/address/phone citations across directories are a core local-ranking signal, and each one is a free backlink from an already-indexed domain.',
    how: 'Submit to: Yellow Pages Malaysia, Bing Places, Apple Business Connect, Foursquare, Waze, Cybo, Malaysia Central, iProperty-style local listings. Keep NAP byte-identical to your Google Business Profile.',
    minutes: 90,
    impact: 'high',
  },
  {
    id: 'reddit-quora',
    phase: 'Backlinks',
    title: 'Answer real questions on Reddit r/malaysia and Quora',
    why: 'This is currently the highest-leverage GEO tactic that exists. Reddit is one of the most heavily weighted sources in both Google AI Overviews and ChatGPT answers. A genuinely useful answer that happens to cite your calculator gets pulled into AI responses.',
    how: 'Search r/MalaysianPF and r/malaysia for "medical card", "MRTA vs MLTA", "life insurance worth it". Give a real, complete answer first. Link your calculator only where it genuinely helps. Never drop a bare link — it gets removed and it does not get cited.',
    link: 'https://www.reddit.com/r/MalaysianPF/',
    minutes: 45,
    impact: 'critical',
  },
  {
    id: 'tiktok-to-site',
    phase: 'Traffic',
    title: 'Route your existing TikTok audience to the site',
    why: 'You already have 3.6K followers on @annacakapinsurans. That is an audience most new sites would pay for. Real visitors who spend time on the page are a ranking signal you cannot buy.',
    how: 'End videos with "calculator link in bio". Make each calculator its own video. Traffic + dwell time + branded searches for "annaprudential" all compound.',
    minutes: 20,
    impact: 'high',
  },
  {
    id: 'youtube-descriptions',
    phase: 'Traffic',
    title: 'Put the URL in YouTube video descriptions',
    why: 'YouTube descriptions are crawled and indexed, and YouTube itself surfaces in Google. A second indexed surface pointing at your domain.',
    how: 'Upload your TikToks as YouTube Shorts. First line of every description: the relevant deep link, not just the homepage.',
    minutes: 20,
    impact: 'medium',
  },
  {
    id: 'wikipedia-adjacent',
    phase: 'GEO',
    title: 'Get cited on high-trust Malaysian finance sites',
    why: 'LLMs weight sources by trust. One mention on RinggitPlus, iMoney, SoyaCincau or a local news site is worth a hundred directory links for AI citation.',
    how: 'Offer a free expert quote or a data-backed comment on medical inflation to Malaysian personal-finance bloggers and journalists. Your medical inflation figures (11.2%–15.9%) are genuinely citable material.',
    minutes: 60,
    impact: 'high',
  },
  {
    id: 'faq-expansion',
    phase: 'GEO',
    title: 'Write pages that answer the exact question people type',
    why: 'AI answers are assembled from pages that match a question literally. "How much does a medical card cost in Malaysia 2026" is a page, not a paragraph.',
    how: 'Use Google autocomplete and the "People also ask" box for your terms. Turn each into an H2 with a one-sentence direct answer underneath. The dashboard flags pages missing this shape.',
    minutes: 60,
    impact: 'high',
  },
  {
    id: 'internal-linking',
    phase: 'SEO',
    title: 'Cross-link guides to calculators and products',
    why: 'Internal links spread authority from whichever page ranks first to the rest of the site, and give crawlers more paths in. The dashboard flags pages with fewer than four.',
    how: 'Every blog post should link to its matching calculator and at least two product pages, using descriptive anchor text — "medical card cost calculator", not "click here".',
    minutes: 45,
    impact: 'medium',
  },
  {
    id: 'analytics',
    phase: 'Measure',
    title: 'Install free analytics',
    why: 'You cannot optimise what you cannot see. GSC shows search; analytics shows what people do once they arrive.',
    how: 'Google Analytics 4 is free. Cloudflare Web Analytics is free and needs no cookie banner, which is the better choice for a lean site.',
    link: 'https://www.cloudflare.com/web-analytics/',
    minutes: 15,
    impact: 'medium',
  },
];

export const PHASES = ['Get indexed', 'Local authority', 'Entity building', 'Backlinks', 'Traffic', 'GEO', 'SEO', 'Measure'];
